### ISSUE TITLE
plot format error 

### ISSUE THREAD

**Issue by vallerrr** [RobustiPy/robustipy#1]
when there are no `specs` in the plot function, 
- the colour of the IC curve is blue (should be black?), also there is no line indicating the place of the full model
- the ax3 title is still there (c in this figure)

![image](https://github.com/RobustiPy/robustipy/assets/36286934/0cd4af57-f523-443d-971e-30eedd5d58d8)

- to replicate: 
`union_results.plot(ic='hqic', figsize=(16, 8))`

**Comment by crahal** [comment]
Yes, the lower right subfigure should always plot the full model. I'll take care of this.

**Comment by vallerrr** [comment]
in the order specification plot (panel e), the full model does not have the vertical line 
<img width="703" alt="image" src="https://github.com/RobustiPy/robustipy/assets/36286934/d826d97c-1563-4e59-b3b8-707366ce5b4f">
