### ISSUE TITLE
Each model run should print or log a wave of useful summary stats

### ISSUE THREAD

**Issue by crahal** [RobustiPy/robustipy#11]
Examples:

* % coefficients with the same sign (e.g. Young and Holsteen style).
* Min and max (and mean?) value of coefficient of interest across all bootstraps and specs.
* The "Best" model selected by user-specified IC

**Comment by vallerrr** [comment]
I edited the summary() function in the OLSRobut class and the current output looks like this ⬇️

<img width="480" alt="image" src="https://github.com/RobustiPy/robustipy/assets/36286934/44f78360-48f8-4ef9-90e1-c4069c4c5af1">

code can be found in the latest commit in  the relevant branch and we @crahal @dhvalden  should think of any other model summary information we want to add to the current function/ format of the print content before merging the branch into main

**Comment by vallerrr** [comment]
updated summary function 
![image](https://github.com/RobustiPy/robustipy/assets/36286934/c2b9d763-dbe5-4803-bf6c-9a9ec5ba8537)
