### ISSUE TITLE
OLS regression - 1-th leading minor of the array is not positive definite imply

### ISSUE THREAD

**Issue by vallerrr** [RobustiPy/robustipy#2]
error occurred when setting  `replace = False` in the union example 

`union_robust.fit(controls=c,draws=200,replace=False)`

![image](https://github.com/RobustiPy/robustipy/assets/36286934/8416bd16-d214-456e-b8e8-42dab311f381)

**Comment by dhvalden** [comment]
fixed byt removing the argument replace for all functions

**Comment by crahal** [comment]
We might want to instead consider keeping `replace==True`, and try\excepting this with np.nans in the exceptions, but I'll leave it as closed for now.
