### ISSUE TITLE
Bootstrapped CIs should probably be LOESS in plot_curve().

### ISSUE THREAD

**Issue by crahal** [RobustiPy/robustipy#9]
Open to discussion here, but going to implement for now.

**Comment by dhvalden** [comment]
I agree, but in the values in the summary_df should be raw values tho.

**Comment by crahal** [comment]
Yep, agree: this is plotted on the fly in plot_curve() now.

**Comment by crahal** [comment]
Reopening to add a function input argument of `loess=False` (where default input is `loess=True`)
